"""
Markdown report generator + GitHub API writer.

Each audit produces a Markdown file committed to a private GitHub repo at:
    reports/{domain}/{timestamp}.md

This serves as the audit ledger — a permanent, browsable record of every
audit run, useful for trend analysis and customer follow-ups.

If GitHub credentials are not configured (env vars missing), the push is
skipped silently. The audit response is unaffected.
"""
import base64
import os
from datetime import datetime, timezone

import httpx


# ─── Markdown generator ───────────────────────────────────────
def generate_markdown(domain, url, score, max_score, categories, checks, ssl_cap, timestamp):
    """
    Render a complete audit as a Markdown document. Includes fix and verify
    fields — this is the full report, suitable for the audit ledger.
    """
    lines = []

    # Header
    lines.append(f"# SVO Audit Report — {domain}")
    lines.append("")
    lines.append(f"**Audited URL:** {url}")
    lines.append(f"**Generated:** {timestamp}")
    lines.append(f"**Score:** {score} / {max_score}")
    if ssl_cap:
        lines.append("")
        lines.append("> ⚠ **Score capped at 40 due to HTTPS/SSL failure.** Resolve SSL before addressing other checks.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Category breakdown
    lines.append("## Category Breakdown")
    lines.append("")
    lines.append("| Category | Score | % |")
    lines.append("|----------|-------|---|")
    for cat_key, cat in categories.items():
        lines.append(f"| {cat['label']} | {cat['score']} / {cat['max']} | {cat['pct']}% |")
    lines.append("")

    # Group checks by status for the summary
    failed = [c for c in checks if c.status == "fail"]
    warned = [c for c in checks if c.status == "warn"]
    passed = [c for c in checks if c.status == "pass"]

    lines.append(f"**Summary:** {len(passed)} passed, {len(warned)} warning, {len(failed)} failed")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Priority fix queue
    problems = sorted(
        [c for c in checks if c.status != "pass"],
        key=lambda c: (c.points_possible - c.points_earned),
        reverse=True,
    )

    if problems:
        lines.append("## Priority Fix Queue")
        lines.append("")
        for c in problems:
            recoverable = c.points_possible - c.points_earned
            status_icon = "❌" if c.status == "fail" else "⚠️"
            lines.append(f"### {status_icon} {c.name} (+{recoverable} pts)")
            lines.append("")
            lines.append(f"**Category:** {c.category} · **Weight:** {c.weight} · **Points:** {c.points_earned} / {c.points_possible}")
            lines.append("")
            lines.append(f"**Finding:** {c.detail}")
            lines.append("")
            if c.fix:
                lines.append(f"**Fix:** {c.fix}")
                lines.append("")
            if c.verify:
                lines.append(f"**Verify:** {c.verify}")
                lines.append("")
            lines.append("---")
            lines.append("")

    # Passed checks
    if passed:
        lines.append("## Passed Checks")
        lines.append("")
        for c in passed:
            lines.append(f"- ✅ **{c.name}** ({c.points_earned}/{c.points_possible}) — {c.detail}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by SVO Auditor v2.0*")
    lines.append("")

    return "\n".join(lines)


# ─── GitHub API writer ────────────────────────────────────────
async def push_to_github(domain, timestamp, markdown_content):
    """
    PUT the markdown file to the configured private reports repo.

    Path format: reports/{domain}/{safe_timestamp}.md
    Uses GitHub's contents API for a single-file commit.
    Fails silently — never blocks the audit response.
    """
    pat = os.environ.get("GITHUB_PAT")
    owner = os.environ.get("GITHUB_REPO_OWNER")
    repo = os.environ.get("GITHUB_REPO_NAME")

    if not pat or not owner or not repo:
        return  # Not configured — skip

    # Sanitize timestamp for filename (no colons on Windows-friendly paths)
    safe_ts = timestamp.replace(":", "-").replace(".", "-")
    path = f"reports/{domain}/{safe_ts}.md"

    endpoint = f"https://api.github.com/repos/{owner}/{repo}/contents/{path}"
    encoded = base64.b64encode(markdown_content.encode("utf-8")).decode("ascii")

    payload = {
        "message": f"audit: {domain} {timestamp}",
        "content": encoded,
        "branch": "main",
    }

    try:
        async with httpx.AsyncClient(timeout=8.0) as client:
            await client.put(
                endpoint,
                headers={
                    "Authorization": f"Bearer {pat}",
                    "Accept": "application/vnd.github+json",
                    "X-GitHub-Api-Version": "2022-11-28",
                },
                json=payload,
            )
    except Exception:
        # Don't break the audit if GitHub is unreachable
        pass
